### ISSUE TITLE
Theme fails Lighthouse test

### ISSUE THREAD

**Issue by haavardnk** [eddiesigner/liebling#351] opened 2021-04-07 13:29 UTC
The theme fails the Lighthouse test in Chrome Dev Tools and Google Page Speed Insight. Happens both for the demo site and for my personal site using this theme. Other themes (tested Casper and Edition) does not have the same error.
Error message: NO_LCP

To replicate:
Run Lighthouse with chrome dev tools with device mobile for https://liebling.eduardogomez.io/
or
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fliebling.eduardogomez.io%2F&hl=en

**Comment by ClassUnwind** [comment] 2021-04-09 00:59
Disabling the [fade animation](https://github.com/eddiesigner/liebling/wiki/How-to-disable-the-fade-animation) makes Lightouse pass on the LCP-test, at least on my end. Unsure of the reason why. Personally not a fan of it anyway, so it works out fine for me, though tracing and fixing the underlying reason would be cool.

**Comment by eddiesigner** [comment] 2021-04-21 21:51
I'm not sure if this is really an issue with the theme itself, I mean, of course Google Page Speed Insight has a problem with the fade animation but is more likely that there is an issue with that tool, I google it and I found that unfortunately that tool has some similar known issues and those get fixed (or appear again) from one version to another. In the future I will try to replace the current library that the theme uses for the fade animation to see if the problem disappears.

**Comment by eddiesigner** [comment] 2022-08-20 20:19
I'm closing this issue since this has been fixed in [the latest version](https://github.com/eddiesigner/liebling/releases/tag/v2.1.0) 👍 

The problem was caused by the [AOS](https://github.com/michalsnik/aos) library, now the theme uses css-only animations instead in order to fix the issue.

**Closed by eddiesigner** 2022-08-20 20:19 UTC
