### ISSUE TITLE
Safari: Article cards and rounded corners bug

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#219] opened 2020-07-03 09:00 UTC
Found a bug with article cards and featured cards. Top rounded corners disappear sometimes when you hover on the card. On Chrome and Firefox it's fine though.

PS: on safari there's a resource that fails to load.

<img width="1440" alt="Screenshot 2020-07-03 at 11 44 39 AM" src="https://user-images.githubusercontent.com/1311831/86451535-b6681180-bd23-11ea-9e23-fe43476ad812.png">

**Comment by nsursock** [comment] 2020-07-06 10:39
Found 2 more bugs. I thought I should let you know.
1/ mobile menu displays recent articles in a weird way
2/ on 800x600, menus don't display correctly.

<img width="1440" alt="bugmenu" src="https://user-images.githubusercontent.com/1311831/86584705-00ecc680-bf8e-11ea-93aa-1bf1689cc4e7.png">
![bugtheme](https://user-images.githubusercontent.com/1311831/86584721-0813d480-bf8e-11ea-8029-1373dd73c9e2.png)

**Comment by eddiesigner** [comment] 2020-07-08 17:44
I was able to reproduce the issue with the featured cards but had no luck with article cards, what version of Safari are you using?

I fixed the issue with the featured cards and now it looks fine:

![CleanShot 2020-07-08 at 19 14 03@2x](https://user-images.githubusercontent.com/1477503/86949612-355bb080-c14f-11ea-82f8-eba2ac972af5.png)

Don't worry about the [source map file](https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/), that's not actually used by the theme, it's just a file that helps when debugging, I guess Safari doesn't load this file because Webpack didn't generate it in the first place since is a third-party library but doesn't affect in any way the performance or something else.

I couldn't reproduce the issue with the recent articles:

![IMG_41DD181AC3BA-1](https://user-images.githubusercontent.com/1477503/86950551-8d46e700-c150-11ea-8de9-1ed8d5ebb1af.jpeg)

I tested on two different iPhone models and everything worked just fine, could've been a cache issue or some weird connection issue?

The issue with the menu is a known issue and won't be solved in the near future since is not really trivial to make the menu adaptable when you have any number of menu items. For now you have two options:

1) Remove some links from the main menu and put them in the secondary menu instead

2) Edit almost all the header-related stylesheets so they use a bigger breakpoint to decide when to display the mobile menu and when to display the menu for desktop.

For example, instead of using `@include respond-to('medium')` they should use `@include respond-to('large')` when needed. These changes will show the mobile version from tablet sizes and below, not from phone sizes as it is now.

The files that would need this change are the following:

![CleanShot 2020-07-08 at 19 41 10](https://user-images.githubusercontent.com/1477503/86952254-00515d00-c153-11ea-95ef-732204f80a86.png)

Note: Please avoid reporting something that is not related to the original issue, for that you can create a different issue.

**Comment by eddiesigner** [comment] 2020-07-22 07:38
I will close this issue for now, please feel free to reopen it if needed.

**Closed by eddiesigner** 2020-07-22 07:38 UTC
Labels: bug
