### ISSUE TITLE
Blogpost Image is resized weirdly on mobile

### ISSUE THREAD

**Issue by MereCivilian** [eddiesigner/liebling#257] opened 2020-08-08 23:55 UTC
Link:
https://merecivilian.com/spotify-connect-on-homepod/
https://merecivilian.com/hannibal/

If you open this image in mobile, the image looks weird. Plus, the resizing on the desktop is also weird. It appears to crop it. I am not sure what exactly it is doing, but the images were fine when used with my previous ghost theme. 

Also, if you go to the home page, https://merecivilian.com/, the images load fine and is complete. When the actual post is opened, the image goes weird. 

Can you please have a look?

**Comment by eddiesigner** [comment] 2020-08-17 17:30
This is not a bug, the image area has a fixed height and loads the image as background. This section uses `background-size: cover` so the background keeps a correct aspect ratio, that's why the images get croped, the idea in this design is not to show the full image but instead having a image area with a constant height across the pages.

It's not possible to mantain a proper aspect ratio with a full-width image while having a fixed height at the same time. If you remove that container and load the image alone in full width then the height of the image would be very long in some screens and that's not the idea of this design. You can see an example of that I mean [here](https://unsplash.com/blog/building-unsplash-studios-during-a-pandemic/).

**Comment by AMeasuredApproach** [comment] 2020-08-25 23:36
Hi Eddie,

Firstly, it's a smart design. Thanks for creating it.

I too am having the same issue as MereCivilian. As it only shows the middle third of the photo, some details get missed (like a dogs face getting cut off). Adjusting the area of one photo won't work as it will affect the appearance of other photos.

Is it possible to increase the height slightly by an inch to incorporate more of the centre of the photo?

Can that be done on my end or only by you?

Thanks again.

**Comment by AMeasuredApproach** [comment] 2020-08-26 05:08
Also, Eddie is there any way of overlaying an image on the landing page so it doesn't have the washed-out look? I'd like to use my logo in that space.

Cheers.

**Comment by eddiesigner** [comment] 2020-08-26 17:01
@AMeasuredApproach Hi,

To increase the height you can head to the Ghost Admin -> Code injection and injecting the following code into the Site Header section:

```html
<style>
@media only screen and (min-width:48rem) {
  .m-hero {
    min-height: 600px !important; /* You can set the height you want here */
  }
}
</style>
```

I didn't understand how do you want to use your logo in that area, can you please elaborate more? If you want to modify somehow the hero component and include your logo somewhere then you will need to make some changes in multiple places, and since that's something that the theme is not prepared for, you will need to implement those changes by yourself, I can't provide support for such customizations, sorry.

**Comment by MereCivilian** [comment] 2020-08-28 05:53
> Also, Eddie is there any way of overlaying an image on the landing page (publication cover) so it doesn't have the washed-out look? I'd like to use my logo in that space.
> 
> Cheers.

**Comment by MereCivilian** [comment] 2020-08-28 05:54
@AMeasuredApproach 

how much did you end up increasing the height?

**Comment by AMeasuredApproach** [comment] 2020-08-28 09:33
Thanks @eddiesigner. The code works well thank you. Disregard the second part of the question. It was more to the fact that the images appear different to those within the post (more faded/washed out in appearance).

@MereCivilian we had a play with the height as some of the details get cut off (dogs faces/that coffee cup with 'begin' which I used also).

Mobile doesn't appear affected, only iPad and desktop. iPad appearance is much taller (almost the whole picture) in general. It's the desktop that it has the most effect on. 

Increasing to 700 is too much for my liking as it cuts off the title of the post on the landing page. I've gone with 670, but that could change. Best to have a play and decide for yourself.

Here is an example between 600 and 670 as an example.
![E41EC5F9-87DB-47F5-A7CD-9F23E8E63878-COLLAGE](https://user-images.githubusercontent.com/68266532/91546053-3b0e8f00-e965-11ea-9764-50562520beb2.jpeg)

**Comment by AMeasuredApproach** [comment] 2020-08-28 09:33
I'd link my site but it's still a work in progress.

**Comment by eddiesigner** [comment] 2020-10-26 17:24
I'm doing some cleaning up so I'll close this issue for now, please feel free to reopen it if needed.

**Closed by eddiesigner** 2020-10-26 17:24 UTC
Labels: wontfix
