### ISSUE TITLE
rounded corners bug

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#251] opened 2020-08-04 12:43 UTC
I already mentioned this bug but I have news: the upper square corner bug only appears on the first 4 cards of the landing page. Afterwards, rounded corners are working fine.
https://soundsirius.digitalpress.blog/

**Comment by eddiesigner** [comment] 2020-08-05 21:27
As I said before, I can't reproduce it, thus I can't provide a fix for it. Have you tried with the theme without customizations? What version of Safari do you have?

Since I can't reproduce it I would ask you if you can try to fix it by yourself and then tell me how you fixed or maybe create a pull request.

Btw, the [latest release](https://github.com/eddiesigner/liebling/releases/tag/v.0.8.5) now allows horizontal scroll in the main menu when you have several links and the window width is small so the links are not longer displayed as you reported [here](https://github.com/eddiesigner/liebling/issues/219#issuecomment-654155709).

**Comment by eddiesigner** [comment] 2020-08-17 17:14
I will close this issue for now, please feel free to reopen it if needed.

**Closed by eddiesigner** 2020-08-17 17:14 UTC
