### ISSUE TITLE
Suppress Twitter

### ISSUE THREAD

**Issue by tomotvos** [eddiesigner/liebling#358] opened 2021-04-17 18:22 UTC
Love the theme so far. One issue is that my site does not have a Twitter URL.  Would it be a straightforward task to make the Twitter links conditional on that?

**Comment by eddiesigner** [comment] 2021-04-20 16:10
To remove the Twitter button you can just clear the url in the Ghost Admin, if the field is empty then the button won't be displayed.

**Comment by tomotvos** [comment] 2021-04-20 16:25
Then that is a bug, because it does not happen that way. Looking at the code, I didn't see conditional tests either.

**Comment by eddiesigner** [comment] 2021-04-20 16:31
[The code](https://github.com/eddiesigner/liebling/blob/72b7d15f3d392741236303d1a9f825dd18912be7/partials/footer.hbs#L18) looks like this:

```hbs
{{#if @site.twitter}}
	<a href="{{twitter_url @site.twitter}}" target="_blank" rel="noopener" aria-label="Twitter">
  		<span class="icon-twitter" aria-hidden="true"></span>
	</a>
{{/if}}
```

Please make sure to save your changes.

**Comment by tomotvos** [comment] 2021-04-20 23:07
Ok, I see that in footer.hbs, but it is missing from post.hbs. Thanks!

**Comment by ClassUnwind** [comment] 2021-04-21 12:24
Just to confirm, you're not talking about removing the "Share" button for Twitter that's on the top(ish) right hand side of the posts, located above the Facebook button, right? That simply links to a preformatted "intent" for Twitter users to post a Tweet where the site's URL are present, not a link to the site's Twitter account as such.

If, however, that's what you would like to remove, then either (a), removing the link in the code, located in `post.hbs`:
https://github.com/eddiesigner/liebling/blob/72b7d15f3d392741236303d1a9f825dd18912be7/post.hbs#L57-L60
Or (b), adding a `<style>` code injection (located at `Settings>Code injection`), where the CSS is something like:
```CSS
<style>
div.m-share > div > a[href^='https://twitter.com/'] { display: none; }
</style>
```

The _site_ Twitter link code is present in the `footer.hbs` file linked above, and it will not be output if it isn't set in `Settings>General>Social accounts` -- ie, left blank. I've verified on my end, running the latest Ghost and Liebling version, that this does work as intended.

There's also the Author who will get a Twitter link added if the corresponding "Staff" member has one set -- but, again, won't be output if not set.

**Comment by eddiesigner** [comment] 2021-05-01 18:16
I will close this issue for now, please feel free to reopen it if needed.

**Closed by eddiesigner** 2021-05-01 18:16 UTC
