### ISSUE TITLE
Locale: In both light and dark mode the tooltip says "Toggle dark mode"

### ISSUE THREAD

**Issue by begonaalvarezd** [eddiesigner/liebling#418] opened 2021-12-02 09:49 UTC
Not a big deal, just a suggestion 🙏🏼 

Perhaps would be better using `switch to dark mode` `switch to light mode` or something like that? 
[Souce](https://github.com/eddiesigner/liebling/blob/6733b5ef6f61f6f00a8a6bd6bf28ea9dd7ed9986/partials/header.hbs#L122)

![image](https://user-images.githubusercontent.com/3624944/144397558-8957bdab-414a-4492-a1ab-3b2484972ca3.png)
![image](https://user-images.githubusercontent.com/3624944/144397574-0ab758d6-aae7-495e-84b2-f4c5c9be981d.png)

**Comment by eddiesigner** [comment] 2021-12-04 21:00
I agree that it would be a better translation, the problem is that we can't change the translations based on the theme appearance, that's why I tried to use a translation that *could* work in both situations. Do you have a suggestion that could work well? 😄

**Comment by yuugatao** [comment] 2021-12-30 18:57
Maybe just simply "Toggle Light/Dark"?

**Comment by ArjoDas** [comment] 2021-12-31 07:29
or just "Light/Dark"?

**Comment by eddiesigner** [comment] 2022-01-03 15:59
Yeah, "Toggle Light/Dark" sounds good, might be even better if we say "Toggle light/dark mode".

I will close this issue since I already updated the translation in the English locale file (and Spanish).

**Closed by eddiesigner** 2022-01-03 15:59 UTC
