### ISSUE TITLE
Really weird submenu icon

### ISSUE THREAD

**Issue by ooohawk** [eddiesigner/liebling#301] opened 2020-12-30 06:36 UTC
Hi there,

I really love your theme but the only problem I have with this theme is that the icon of the submenu becomes really big

![screenshot](https://user-images.githubusercontent.com/43295730/103334257-a8653480-4aab-11eb-9b77-8b639a1778d6.png)

I'm not sure if it is mine problem or there's something wrong with the theme. 
BTW, it works great on safari and Firefox, the sizing error only exists on chromium-based browser. (or if there's any way to disable that three dot?)

**Comment by eddiesigner** [comment] 2020-12-30 11:41
Hi,

This is weird, I can't reproduce it on Chrome nor Brave, it happens to you also in the demo website? https://liebling.eduardogomez.io/

Would you mind to send me a link to your website so I can see it? Also, what version of this theme are you using?

**Comment by ooohawk** [comment] 2021-01-01 18:42
Hi there,

Sorry for the late response. Yes, the bug remains existing in the demo website. Here's a screenshot on macOS(the previous one was shot on windows) with demo website on safari, chrome, edge (top to bottom)
![截屏2021-01-02 上午2 34 49](https://user-images.githubusercontent.com/43295730/103444435-19227180-4ca3-11eb-92d8-9a23d39bfe22.png)

My blog was using 0.8.8 and had this problem then I thought it might be fixed in the latest one, but it turns out that 0.9.0 still have it.

Please let me know if there's any file that would help you, I'll send it to you ASAP.

**Comment by eddiesigner** [comment] 2021-01-04 14:59
I couldn't reproduce it but I updated the icons, it should be fixed in the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.9.1).

**Comment by eddiesigner** [comment] 2021-01-15 21:50
I'm closing this issue now, please feel free to reopen it if needed.

**Closed by eddiesigner** 2021-01-15 21:50 UTC
