### ISSUE TITLE
Support for members

### ISSUE THREAD

**Issue by XxPoNaGeXx** [eddiesigner/liebling#83] opened 2019-11-13 19:03 UTC
Add support for memebrs ghost 3.0? 

I can see all paid posts even when logged out

**Comment by Xenonstaforums** [comment] 2019-11-13 20:10
Check this out dude! [https://github.com/eddiesigner/liebling/issues/70](https://github.com/eddiesigner/liebling/issues/70)

**Comment by eddiesigner** [comment] 2019-11-18 13:48
Duplicate of https://github.com/eddiesigner/liebling/issues/70

**Closed by eddiesigner** 2019-11-18 13:48 UTC
Labels: duplicate
