### ISSUE TITLE
Code blocks are not dark mode compatible

### ISSUE THREAD

**Issue by adityapatadia** [eddiesigner/liebling#203] opened 2020-06-06 17:00 UTC

**Comment by eddiesigner** [comment] 2020-06-07 10:23
Liebling has a pretty basic style for code blocks which is compatible with dark mode, however, if you're using [Prism](https://github.com/eddiesigner/liebling/wiki/Add-syntax-highlighting-with-Prism) or something like that for syntax highlighting then the issue is on their side.

**Comment by adityapatadia** [comment] 2020-06-07 13:07
Nothing is used for syntax highlighting. I will send screenshot.

**Comment by eddiesigner** [comment] 2020-06-22 15:31
I will close this for now, please feel free to reopen it if needed.

**Closed by eddiesigner** 2020-06-22 15:31 UTC
