### ISSUE TITLE
the currently active theme "liebling" is missing.

### ISSUE THREAD

**Issue by keyuls** [eddiesigner/liebling#124] opened 2020-01-09 21:33 UTC
This happens two times in three days. Suddenly theme miss from the blog.

![image](https://user-images.githubusercontent.com/8844721/72105599-15a41680-32eb-11ea-8abd-d3e80f8cbab2.png)

When I checked inside the design section. The uploaded theme is not showing anymore
![image](https://user-images.githubusercontent.com/8844721/72105639-2d7b9a80-32eb-11ea-8940-bc2062b0efde.png)

**Comment by eddiesigner** [comment] 2020-01-10 10:39
I really don't think this is related to the theme itself. If there is something wrong with the theme at leats you will be able to see it in that list.

Could be an issue with your node version or some issue with permissions?

It also happens if you install a different theme?

Can you try to see the logs? https://ghost.org/docs/api/v3/ghost-cli/help/

**Comment by patrickphatnguyen** [comment] 2020-01-10 14:02
I think you're deploying on a heroku container if that's right. If you use a container-based service make sure to clarify Liebling theme packing in the installation so everytime the container restarts it won't lose contents (such as themes)

**Comment by eddiesigner** [comment] 2020-01-16 08:28
I will close this for now, please feel free to reopen it if you think is necessary.

**Closed by eddiesigner** 2020-01-16 08:28 UTC

**Comment by keyuls** [comment] 2020-01-21 21:57
@patrickphatnguyen is right. I  have verified it. On Heroku when dyno restart, it removes uploaded packages including theme and even redirects JSON file. 

@patrickphatnguyen  do you know how to clarify the Liebling theme package in the installation?

**Comment by keyuls** [comment] 2020-01-21 23:46
so I followed this[ package.json](https://github.com/SNathJr/ghost-on-heroku/blob/master/package.json) file and added 
`    "liebling": "github:eddiesigner/liebling#v.0.6.4",
`

It worked. After restarting dyno, it shows the theme in the installed theme list:
![image](https://user-images.githubusercontent.com/8844721/72852826-fd2de780-3c6c-11ea-8b3b-1bed745b5c3a.png)


but when I activate it, it doesn't display correctly on the blog and it shows errors in the console:
![image](https://user-images.githubusercontent.com/8844721/72852924-49792780-3c6d-11ea-9291-e6b83b2c5ea7.png)


This is happening only with the Liebling theme. All other themes are working properly.

Any suggestions on how to fix it?

**Comment by patrickphatnguyen** [comment] 2020-01-22 03:32
Hi @keyuls, could you show me the link to your git repo of your ghost webiste?

**Comment by eddiesigner** [comment] 2020-01-23 09:45
@keyuls I don't know how that project works but I guess the problem is because they try to clone the repository, that's not the correct way to download this theme, they have to download the latest version from the release links, for example: https://github.com/eddiesigner/liebling/releases/download/v.0.6.5/liebling.zip

Those assets are not part of this repository since they are generated when I release a new version.

As alternative you can download the latest release and create a new repository where you upload the files the zip file contains.

**Comment by keyuls** [comment] 2020-08-13 17:48
@patrickphatnguyen this is my repo 
https://github.com/keyuls/ghost-on-heroku

Please look into it and let me know where should I put Liebling theme, so it doesn't miss on server restart
