### ISSUE TITLE
Progress indicator stuck at about 25-30% until end of article

### ISSUE THREAD

**Issue by darranhall** [eddiesigner/liebling#117] opened 2020-01-05 14:29 UTC
There's this interesting issue on Firefox where the progress indicator will not move past a certain percentage until you reach the end of the article. I can't exactly track down why, but you may have a better idea of what's going on. A screengrab can be provided if needed.

**Comment by eddiesigner** [comment] 2020-01-07 10:57
I can't reproduce it, what Firefox version and platform are you using? A screengrab would be nice but a page link would be even better.

**Comment by youngpilot** [comment] 2020-01-07 11:06
I encountered a similar bug, that possibly has a similar origin:
When using the theme on Mobile Safari on iOS13.1 on iPhoneXR with [hidden Safari User Interface Components](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html), the progress indicator doesn't follow it's circular path and goes to roughly 30%.
![IMG_7209](https://user-images.githubusercontent.com/15856506/71891015-e56f4300-3145-11ea-91c8-47c1ba592b10.png)

This bug doesnt happen when not hiding/showing the Safari UI Components:
![IMG_7220](https://user-images.githubusercontent.com/15856506/71891084-13548780-3146-11ea-9556-09664b488002.png)

**Comment by darranhall** [comment] 2020-01-12 09:46
@eddiesigner I don't have the theme loaded up at the moment on said blog, but I'm on Firefox 72.0.1. I can't say it's related to above poster, but it is strange and sort of distracting haha. I'll try it on another blog I'm setting up and let you see it in action.

**Comment by CptDoraemon** [comment] 2020-01-21 05:35
I'm able to reproduce the issue in the Firefox on Windows.
It looks like the circle is cut off by a square, add a viewBox attribute to the SVG element might help.
I cannot reproduce the issue @youngpilot mentioned, but it looks like a viewBox problem too.
![Untitled](https://user-images.githubusercontent.com/16277928/72778111-e0020600-3be5-11ea-96d1-4000aa100a9c.png)

**Comment by eddiesigner** [comment] 2020-01-22 12:00
I already merged the changes from @CptDoraemon (thanks again) 😉 that should fix those issues. Please download the latest version https://github.com/eddiesigner/liebling/releases/tag/v.0.6.5

**Comment by eddiesigner** [comment] 2020-02-03 08:35
I will close this for now, please feel free to reopen it if needed.

**Closed by eddiesigner** 2020-02-03 08:35 UTC
