### ISSUE TITLE
Support members feature from Ghost 3.0

### ISSUE THREAD

**Issue by emadalam** [eddiesigner/liebling#70] opened 2019-10-23 10:44 UTC
With the release of [Ghost 3.0](https://ghost.org/3/) we now have the capability for [member login](https://ghost.org/docs/members/introduction/). Though there are many aspects to consider to fully support the membership feature in a theme, the logical start could be with the basic setup for [signin/signup forms](https://ghost.org/docs/members/signup-signin-forms/) that would allow the sites to let users register on their websites. I was able to get it working without any styles etc, by just creating a page from Ghost admin with following embedded html.

```html
<form data-members-form>
  <input data-members-email type="email" required="true"/>
  <button type="submit">Continue</button>
</form>
```

The following would be great to have as the first steps.
- Login/logout button if member feature is enabled
- Styled singin/signup pages

**Comment by ljgrohn** [comment] 2019-10-23 15:56
Since this theme already has a pretty robust signup/subscription integration that might be a great place to start. It used to only be enabled when the "subscription" box was ticked in Labs, but maybe it could be switched to being on when the memberships portion is turned on?

**Comment by najcardboyz** [comment] 2019-11-04 09:06
That's right, it looks amazing if this feature is on themes

**Comment by eddiesigner** [comment] 2019-11-10 17:22
I'm excited about this feature too but I think is better if I wait a bit more because for now it's a *beta* version which means, there are some bugs, some things could change and people is requesting more features.

For example, at the moment you can't cancel your subscription if you want to. Also the regular subscription feature was replaced by this one.

I'll definetely integrate this feature but not now, I hope I'll do it at the beginning of next year if everything is more stable.

**Comment by pilotviper134** [comment] 2020-02-11 18:42
Any update?

**Comment by eddiesigner** [comment] 2020-02-13 11:58
Not yet, I have plans to work on this later this month but it would take some time to give support to all the new features that Ghost 3 already have, so maybe I will create small releases with a new feature at a time.

**Comment by roniemartinez** [comment] 2020-02-23 10:39
Hi @eddiesigner 

In the new version of Ghost, the subscribe button is missing from liebling. The reason was it was changed to `@labs.members` (see [Casper](https://github.com/TryGhost/Casper/blob/c27fc17844e287d5e6aa575d3ea4b6b9d80f88f3/default.hbs#L44)) while liebling is still using `@labs.subscribers`.

Unfortunately, I am one of the users of the new Ghost version + liebling.

**Comment by TheAmayJain** [comment] 2020-03-07 20:54
> Hi @eddiesigner
> 
> In the new version of Ghost, the subscribe button is missing from liebling. The reason was it was changed to `@labs.members` (see [Casper](https://github.com/TryGhost/Casper/blob/c27fc17844e287d5e6aa575d3ea4b6b9d80f88f3/default.hbs#L44)) while liebling is still using `@labs.subscribers`.
> 
> Unfortunately, I am one of the users of the new Ghost version + liebling.

_ How to get this subscribe button again?_

**Comment by roniemartinez** [comment] 2020-03-08 01:23
@TheAmayJain it's in the wiki

**Comment by TheAmayJain** [comment] 2020-03-08 04:23
I don't think so, I didn't found it. Can you be more specific? I'm currently using button down, but I don't think it's working, anyways.

**Comment by roniemartinez** [comment] 2020-03-08 04:26
@TheAmayJain https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers

Although it will not work on new Ghost versions because liebling does not support it.

**Comment by TheAmayJain** [comment] 2020-03-08 04:27
Ik this one, but now it's not Subscribers, it's members, so.

**Comment by roniemartinez** [comment] 2020-03-08 04:29
> Ik this one, but now it's not Subscribers, it's members, so.

Exactly! (see my previous [comment](https://github.com/eddiesigner/liebling/issues/70#issuecomment-590054648)). 

That's why it is not possible to get members in liebling. This feature should be on the top priority list.

**Comment by eddiesigner** [comment] 2020-03-09 23:15
I already started working on the subscription form, it should be ready in the following days or next week. Although giving full support to member functionality will take more time because it involves designing and developing several more screens and I don't have much spare time at the moment 😟

**Comment by TheAmayJain** [comment] 2020-03-10 04:45
Great, by no means I was saying anything to you personally btw. Can't wait to see.😊

**Comment by TheAmayJain** [comment] 2020-03-12 17:25
Where will we get to know about the updates?

**Comment by eddiesigner** [comment] 2020-03-12 22:31
You can see the progress here: https://github.com/eddiesigner/liebling/commits/master (it's almost finished)

I will let you know guys when the new subscription feature is ready on this thread.

**Comment by TheAmayJain** [comment] 2020-03-13 07:17
Great thanks 🤗

**Comment by eddiesigner** [comment] 2020-03-16 19:44
I just released [version 0.6.6](https://github.com/eddiesigner/liebling/releases/tag/v.0.6.6) which gives support to Ghost 3 and the new subscribers form 📢 

To learn how to enable it please read this: https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers

_Note: From now on, this theme is only compatible with Ghost 3+. Please also note that this new version supports only the subscribers functionality, not all the members functionality (login, registration, payments, etc.)_

**Comment by TheAmayJain** [comment] 2020-03-17 09:38
Can you include screenshots, because I don't seem to find how to enable, I did what you told in page, i created a page named Newsletter with link... Https://mysiteurl/newsletter
But it doesn't seem to work

*P.s. I use buttondown already for subscribers

**Comment by eddiesigner** [comment] 2020-03-17 15:52
There is no need to include screenshots, you just need to make sure you're using Ghost 3 in order to see the Members option in the Ghost admin. You can see it working here: https://liebling.eduardogomez.io/

**Comment by TheAmayJain** [comment] 2020-03-17 15:55
I have done it but it isn't working 😭

**Comment by TheAmayJain** [comment] 2020-03-17 15:59
I am on ghost 3 what I did is...

Create a page named Newsletter and link, inmycase https://VatsalAmay.digitalpress.blog/newsletter

You can see it isn't working.

**Comment by eddiesigner** [comment] 2020-03-17 16:06
Well, I just saw that you don't have the [latest version](https://github.com/eddiesigner/liebling/releases/tag/v.0.6.6) of this theme. I inspected the source code of your website and the new code is not there, that's why it's not working for you.

You have to download the latest version and upload it to your Ghost instance.

**Comment by TheAmayJain** [comment] 2020-03-17 16:21
But if that theme is officially in ghost then should not ghost update it by itself for all? Because if you own the theme and you make changes, then I think thy should let you make changes and updates to the theme officially 🙊

**Comment by timscha** [comment] 2020-03-17 19:14
I can confirm it is working. Thank you very much @eddiesigner for this great update! :)

**Comment by eddiesigner** [comment] 2020-03-17 20:07
@TheAmayJain The fact that this theme is listed in the Ghost themes marketplace doesn't mean that it's gonna be updated it automatically, as any other theme you have to do it by yourself, that's how it works.

**Comment by eddiesigner** [comment] 2020-03-17 20:10
@timscha Thank you for confirming it!

**Comment by zanderman44** [comment] 2020-05-05 15:20
@eddiesigner, I'm new to Ghost and I really like your theme. However, I'm looking to use Ghost for a membership site and after reading this thread I'm wondering if that's possible using your theme? Will you be adding membership functionality anytime soon?

**Comment by eddiesigner** [comment] 2020-05-07 16:49
I am afraid that at the moment it is not possible to have memberships and it may not be something I will develop in the near future, sorry 😓

**Comment by zanderman44** [comment] 2020-05-07 18:05
Thanks for your reply. Today I purchased your Weiss Pro theme as it does have the membership components.

**Comment by FarazPatankar** [comment] 2020-05-20 03:42
Hey @eddiesigner,

Been using this theme for a while now and really enjoying it. I noticed you mentioned earlier that you won't be adding memberships to this theme. Could you shed some light on why?

I am more than happy to help implement it if time is the issue. If it's a more personal decision and a differentiator between this and your paid theme, I completely understand.

**Comment by eddiesigner** [comment] 2020-05-22 20:16
@FarazPatankar Maybe I will implement memberships on this theme in some point but not now. The memberships didn't exist when I released it so I never thought about that.

It's true that time could be a reason but it's more about the changes that I have to implement in the layout and because I have to think how to design the pages and components involved, actually there is some code already implemented and ready but still there is a lot of work to do, mainly design stuff.

**Comment by DawnImpulse** [comment] 2020-08-19 15:18
any updates on membership functionality?

**Comment by alinbarla87** [comment] 2020-10-30 09:11
I just implemented membership into this theme if anyone needs it can contact me

**Comment by timscha** [comment] 2020-10-30 09:12
> I just implemented membership into this theme if anyone needs it can contact me

Why not sharing in public/as PR as this theme was provided you for free also?

**Comment by eddiesigner** [comment] 2020-11-07 21:03
Ghost is introducing a new feature called [Portal](https://ghost.org/changelog/portal/).

> The latest addition to our beta Members feature is Portal — an embeddable user interface that can be inserted on any Ghost site, using any theme, without needing to write code or edit your theme templates.

I haven't tested it myself but it could be an alternative ;)

**Comment by jazzminewang** [comment] 2020-12-11 05:24
Thanks so much Eddie for this!
One question - I'm getting this error: https://share.getcloudapp.com/7KubPBE5
Do you have any idea why? I'm setup on Mailgun. This is at https://copysmith.ai/resources/newsletter.

**Comment by eddiesigner** [comment] 2020-12-11 12:34
@jazzminewang Hi 👋🏻

If you are only interested in the newsletter form you can simply follow [this guide](https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers), don't need to setup Mailgun or anything else.

Otherwise, if you want to use all the members features then you can use Portal, I mean, you can still use it if you are only interested in the newsletter, in that case you have to enable the members feature in the Ghost Admin to make it work. Please refer to [this guide](https://ghost.org/docs/members/setup/) for more info.

**Closed** 2021-10-12 14:51 UTC
