### ISSUE TITLE
Vertical Alignment in the menu bar

### ISSUE THREAD

**Issue by xdivby0** [eddiesigner/liebling#373] opened 2021-05-19 21:42 UTC
![grafik](https://user-images.githubusercontent.com/53540163/118884545-e649e480-b8f6-11eb-9964-74a9f38c23f8.png)

This happens when there are too many items in the navbar (they don't have to overflow). When I hover over the darkmode switch, they move and suddenly are in the correct position until I reload the page. 

I found out what happens on hover and added some classes to the header div / nav - looks good to me, but I don't know if this could possibly have some side effects. I will create a PR for this and maybe someone who knows this project better can see if it'll work :)

**Comment by eddiesigner** [comment] 2021-05-24 18:44
Hi,

I can't reproduce the issue, the nav bar is correctly vertical aligned on Chrome, Firefox, Safari and Edge. Did you added custom styles or something like that? 

Actually the idea is that you can scroll when there are too many items in the nav bar.

I suggest you to download the latest version from here: https://github.com/eddiesigner/liebling/releases/tag/v1.0.4

**Comment by xdivby0** [comment] 2021-05-26 14:51
I'll put up a test ghost instance with a freshly downloaded theme and try to replicate the issue there and I'll past the link in here then. Could take a few days though, can you leave this open?

**Comment by eddiesigner** [comment] 2021-06-17 18:28
I will close this issue for now, please feel free to reopen it if needed.

**Closed by eddiesigner** 2021-06-17 18:28 UTC
